### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/infografia-de-las-librerias-christopheremv#3]
[Infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-christopheremv/files/6341173/Infografia.pdf)

**Comment by josealfredo79** [comment]
Esta falta evaluarla, por favor para que se asigne la calificación por quien evaluó.

**Comment by Band-hi** [comment]
Calificación: 19/20

-Subir la infografía como issue, dado que no es código.
-No hay fuentes bibliográficas.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
